name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: generalBenmalek
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Algiers
          config_padding: 10%
          config_output: default
          config_twemoji: yes

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: custom
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_display: absolute

          plugin_contributors: yes
          plugin_contributors_base: commits
          plugin_contributors_head: master

          # Commit visualization as tree
          plugin_calendar: yes
          plugin_calendar_limit: 1